// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/rtemb/srv-users/internal/handler"
	"github.com/rtemb/srv-users/internal/storage"
	srv_users "github.com/rtemb/srv-users/pkg/client/srv-users"
)

type ServiceHandlerMock struct {
	AddRoleStub        func(context.Context, string, srv_users.Role) error
	addRoleMutex       sync.RWMutex
	addRoleArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 srv_users.Role
	}
	addRoleReturns struct {
		result1 error
	}
	addRoleReturnsOnCall map[int]struct {
		result1 error
	}
	AuthStub        func(context.Context, string, string) (string, error)
	authMutex       sync.RWMutex
	authArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	authReturns struct {
		result1 string
		result2 error
	}
	authReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	CreateUserStub        func(context.Context, storage.User) error
	createUserMutex       sync.RWMutex
	createUserArgsForCall []struct {
		arg1 context.Context
		arg2 storage.User
	}
	createUserReturns struct {
		result1 error
	}
	createUserReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ServiceHandlerMock) AddRole(arg1 context.Context, arg2 string, arg3 srv_users.Role) error {
	fake.addRoleMutex.Lock()
	ret, specificReturn := fake.addRoleReturnsOnCall[len(fake.addRoleArgsForCall)]
	fake.addRoleArgsForCall = append(fake.addRoleArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 srv_users.Role
	}{arg1, arg2, arg3})
	fake.recordInvocation("AddRole", []interface{}{arg1, arg2, arg3})
	fake.addRoleMutex.Unlock()
	if fake.AddRoleStub != nil {
		return fake.AddRoleStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.addRoleReturns
	return fakeReturns.result1
}

func (fake *ServiceHandlerMock) AddRoleCallCount() int {
	fake.addRoleMutex.RLock()
	defer fake.addRoleMutex.RUnlock()
	return len(fake.addRoleArgsForCall)
}

func (fake *ServiceHandlerMock) AddRoleCalls(stub func(context.Context, string, srv_users.Role) error) {
	fake.addRoleMutex.Lock()
	defer fake.addRoleMutex.Unlock()
	fake.AddRoleStub = stub
}

func (fake *ServiceHandlerMock) AddRoleArgsForCall(i int) (context.Context, string, srv_users.Role) {
	fake.addRoleMutex.RLock()
	defer fake.addRoleMutex.RUnlock()
	argsForCall := fake.addRoleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ServiceHandlerMock) AddRoleReturns(result1 error) {
	fake.addRoleMutex.Lock()
	defer fake.addRoleMutex.Unlock()
	fake.AddRoleStub = nil
	fake.addRoleReturns = struct {
		result1 error
	}{result1}
}

func (fake *ServiceHandlerMock) AddRoleReturnsOnCall(i int, result1 error) {
	fake.addRoleMutex.Lock()
	defer fake.addRoleMutex.Unlock()
	fake.AddRoleStub = nil
	if fake.addRoleReturnsOnCall == nil {
		fake.addRoleReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addRoleReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ServiceHandlerMock) Auth(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.authMutex.Lock()
	ret, specificReturn := fake.authReturnsOnCall[len(fake.authArgsForCall)]
	fake.authArgsForCall = append(fake.authArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	fake.recordInvocation("Auth", []interface{}{arg1, arg2, arg3})
	fake.authMutex.Unlock()
	if fake.AuthStub != nil {
		return fake.AuthStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.authReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ServiceHandlerMock) AuthCallCount() int {
	fake.authMutex.RLock()
	defer fake.authMutex.RUnlock()
	return len(fake.authArgsForCall)
}

func (fake *ServiceHandlerMock) AuthCalls(stub func(context.Context, string, string) (string, error)) {
	fake.authMutex.Lock()
	defer fake.authMutex.Unlock()
	fake.AuthStub = stub
}

func (fake *ServiceHandlerMock) AuthArgsForCall(i int) (context.Context, string, string) {
	fake.authMutex.RLock()
	defer fake.authMutex.RUnlock()
	argsForCall := fake.authArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *ServiceHandlerMock) AuthReturns(result1 string, result2 error) {
	fake.authMutex.Lock()
	defer fake.authMutex.Unlock()
	fake.AuthStub = nil
	fake.authReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ServiceHandlerMock) AuthReturnsOnCall(i int, result1 string, result2 error) {
	fake.authMutex.Lock()
	defer fake.authMutex.Unlock()
	fake.AuthStub = nil
	if fake.authReturnsOnCall == nil {
		fake.authReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.authReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ServiceHandlerMock) CreateUser(arg1 context.Context, arg2 storage.User) error {
	fake.createUserMutex.Lock()
	ret, specificReturn := fake.createUserReturnsOnCall[len(fake.createUserArgsForCall)]
	fake.createUserArgsForCall = append(fake.createUserArgsForCall, struct {
		arg1 context.Context
		arg2 storage.User
	}{arg1, arg2})
	fake.recordInvocation("CreateUser", []interface{}{arg1, arg2})
	fake.createUserMutex.Unlock()
	if fake.CreateUserStub != nil {
		return fake.CreateUserStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.createUserReturns
	return fakeReturns.result1
}

func (fake *ServiceHandlerMock) CreateUserCallCount() int {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	return len(fake.createUserArgsForCall)
}

func (fake *ServiceHandlerMock) CreateUserCalls(stub func(context.Context, storage.User) error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = stub
}

func (fake *ServiceHandlerMock) CreateUserArgsForCall(i int) (context.Context, storage.User) {
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	argsForCall := fake.createUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ServiceHandlerMock) CreateUserReturns(result1 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	fake.createUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *ServiceHandlerMock) CreateUserReturnsOnCall(i int, result1 error) {
	fake.createUserMutex.Lock()
	defer fake.createUserMutex.Unlock()
	fake.CreateUserStub = nil
	if fake.createUserReturnsOnCall == nil {
		fake.createUserReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createUserReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ServiceHandlerMock) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addRoleMutex.RLock()
	defer fake.addRoleMutex.RUnlock()
	fake.authMutex.RLock()
	defer fake.authMutex.RUnlock()
	fake.createUserMutex.RLock()
	defer fake.createUserMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ServiceHandlerMock) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.ServiceHandler = new(ServiceHandlerMock)
