version: '3'
services:
  #  svr-users:
  #    container_name: svr-users
  #    restart: always
  #    build:
  #      context: ./
  #    ports:
  #      - "8081:8080"
  #    environment:
  #      - TOKEN_KEY=ZehL4zUy-3hMSBKWdfnv86aCsnFowOp0Syz1juAjN8U=
  #      - LOG_LEVEL=trace
  #    depends_on:
  #      - redis
  redis:
    container_name: redis
    image: redis:5.0-alpine
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
