// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv-users/server.proto

package srv_users

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_UNKNOWN    Role = 0
	Role_USER       Role = 1
	Role_USER_ADMIN Role = 2
)

var Role_name = map[int32]string{
	0: "UNKNOWN",
	1: "USER",
	2: "USER_ADMIN",
}

var Role_value = map[string]int32{
	"UNKNOWN":    0,
	"USER":       1,
	"USER_ADMIN": 2,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_06b3dfd906dd5a6a, []int{0}
}

type ResponseStateCode int32

const (
	ResponseStateCode_CREATED ResponseStateCode = 0
)

var ResponseStateCode_name = map[int32]string{
	0: "CREATED",
}

var ResponseStateCode_value = map[string]int32{
	"CREATED": 0,
}

func (x ResponseStateCode) String() string {
	return proto.EnumName(ResponseStateCode_name, int32(x))
}

func (ResponseStateCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_06b3dfd906dd5a6a, []int{1}
}

type AddRoleRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Role                 Role     `protobuf:"varint,2,opt,name=role,proto3,enum=srv.users.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRoleRequest) Reset()         { *m = AddRoleRequest{} }
func (m *AddRoleRequest) String() string { return proto.CompactTextString(m) }
func (*AddRoleRequest) ProtoMessage()    {}
func (*AddRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3dfd906dd5a6a, []int{0}
}

func (m *AddRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoleRequest.Unmarshal(m, b)
}
func (m *AddRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoleRequest.Marshal(b, m, deterministic)
}
func (m *AddRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoleRequest.Merge(m, src)
}
func (m *AddRoleRequest) XXX_Size() int {
	return xxx_messageInfo_AddRoleRequest.Size(m)
}
func (m *AddRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoleRequest proto.InternalMessageInfo

func (m *AddRoleRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddRoleRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_UNKNOWN
}

type AuthRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3dfd906dd5a6a, []int{1}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3dfd906dd5a6a, []int{2}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *AuthResponse) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3dfd906dd5a6a, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Company              string   `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3dfd906dd5a6a, []int{4}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type CreateUserResponse struct {
	StateCode            ResponseStateCode `protobuf:"varint,1,opt,name=stateCode,proto3,enum=srv.users.ResponseStateCode" json:"stateCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06b3dfd906dd5a6a, []int{5}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetStateCode() ResponseStateCode {
	if m != nil {
		return m.StateCode
	}
	return ResponseStateCode_CREATED
}

func init() {
	proto.RegisterEnum("srv.users.Role", Role_name, Role_value)
	proto.RegisterEnum("srv.users.ResponseStateCode", ResponseStateCode_name, ResponseStateCode_value)
	proto.RegisterType((*AddRoleRequest)(nil), "srv.users.AddRoleRequest")
	proto.RegisterType((*AuthRequest)(nil), "srv.users.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "srv.users.AuthResponse")
	proto.RegisterType((*Error)(nil), "srv.users.Error")
	proto.RegisterType((*CreateUserRequest)(nil), "srv.users.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "srv.users.CreateUserResponse")
}

func init() { proto.RegisterFile("srv-users/server.proto", fileDescriptor_06b3dfd906dd5a6a) }

var fileDescriptor_06b3dfd906dd5a6a = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x51, 0x6f, 0xd3, 0x3c,
	0x14, 0x6d, 0xd6, 0x74, 0x6d, 0x6f, 0xa7, 0x7e, 0xd9, 0xd5, 0xa7, 0x12, 0x02, 0x48, 0x51, 0x78,
	0xa9, 0x26, 0x2d, 0x95, 0xca, 0x13, 0x48, 0x80, 0xaa, 0x2e, 0x0f, 0xd3, 0x44, 0x41, 0x2e, 0x15,
	0x8f, 0x53, 0xd6, 0x5c, 0x46, 0x44, 0x5a, 0x07, 0xdb, 0x09, 0xda, 0x1f, 0xe5, 0xf7, 0x20, 0x3b,
	0x49, 0x17, 0x54, 0xf1, 0xc2, 0x9b, 0xef, 0x39, 0xe7, 0x1e, 0x1f, 0xdb, 0xd7, 0x30, 0x91, 0xa2,
	0xbc, 0x2c, 0x24, 0x09, 0x39, 0x93, 0x24, 0x4a, 0x12, 0x61, 0x2e, 0xb8, 0xe2, 0x38, 0x94, 0xa2,
	0x0c, 0x0d, 0xee, 0x3d, 0xbb, 0xe7, 0xfc, 0x3e, 0xa3, 0x99, 0x21, 0xee, 0x8a, 0xaf, 0x33, 0xda,
	0xe5, 0xea, 0xa1, 0xd2, 0x05, 0xd7, 0x30, 0x5e, 0x24, 0x09, 0xe3, 0x19, 0x31, 0xfa, 0x51, 0x90,
	0x54, 0x88, 0x60, 0x17, 0x45, 0x9a, 0xb8, 0x96, 0x6f, 0x4d, 0x87, 0xcc, 0xac, 0xf1, 0x25, 0xd8,
	0x82, 0x67, 0xe4, 0x9e, 0xf8, 0xd6, 0x74, 0x3c, 0xff, 0x2f, 0x3c, 0x98, 0x87, 0xa6, 0xd3, 0x90,
	0xc1, 0x7b, 0x18, 0x2d, 0x0a, 0xf5, 0xad, 0xf1, 0xf9, 0x1f, 0x7a, 0xb4, 0x8b, 0xd3, 0xac, 0x36,
	0xaa, 0x0a, 0xf4, 0x60, 0x90, 0xc7, 0x52, 0xfe, 0xe4, 0x22, 0x31, 0x6e, 0x43, 0x76, 0xa8, 0x83,
	0x04, 0xce, 0x2a, 0x03, 0x99, 0xf3, 0xbd, 0x24, 0xed, 0xa0, 0xf8, 0x77, 0xda, 0x37, 0x0e, 0xa6,
	0xd0, 0x68, 0x19, 0x67, 0x69, 0xd5, 0x3e, 0x60, 0x55, 0x81, 0x53, 0x38, 0x25, 0x21, 0xb8, 0x90,
	0x6e, 0xd7, 0xef, 0x4e, 0x47, 0x73, 0xa7, 0x95, 0x31, 0xd2, 0x04, 0xab, 0xf9, 0xe0, 0x2d, 0xf4,
	0x0c, 0xa0, 0x0f, 0xba, 0xe5, 0x09, 0x19, 0xf7, 0x1e, 0x33, 0x6b, 0xf4, 0x61, 0x94, 0x90, 0xdc,
	0x8a, 0x34, 0x57, 0x29, 0xdf, 0xd7, 0x09, 0xdb, 0x50, 0x70, 0x0b, 0xe7, 0x4b, 0x41, 0xb1, 0xa2,
	0x8d, 0x24, 0xf1, 0xcf, 0x67, 0x45, 0x17, 0xfa, 0x5b, 0xbe, 0xcb, 0xe3, 0xfd, 0x83, 0xdb, 0x35,
	0x54, 0x53, 0x06, 0x9f, 0x00, 0xdb, 0x1b, 0xd4, 0x77, 0xf1, 0x06, 0x86, 0x52, 0xc5, 0x8a, 0x96,
	0x4d, 0xe2, 0xf1, 0xfc, 0x79, 0xfb, 0x19, 0x6a, 0xdd, 0xba, 0xd1, 0xb0, 0x47, 0xf9, 0xc5, 0x25,
	0xd8, 0xfa, 0x99, 0x70, 0x04, 0xfd, 0xcd, 0xea, 0x66, 0xf5, 0xf1, 0xcb, 0xca, 0xe9, 0xe0, 0x00,
	0xec, 0xcd, 0x3a, 0x62, 0x8e, 0x85, 0x63, 0x00, 0xbd, 0xba, 0x5d, 0x5c, 0x7d, 0xb8, 0x5e, 0x39,
	0x27, 0x17, 0x3e, 0x9c, 0x1f, 0xd9, 0xe9, 0xde, 0x25, 0x8b, 0x16, 0x9f, 0xa3, 0x2b, 0xa7, 0x33,
	0xff, 0x65, 0xc1, 0x99, 0x4e, 0x27, 0xd7, 0x24, 0xca, 0x74, 0x4b, 0x78, 0x03, 0xf0, 0x98, 0x19,
	0xdb, 0xc1, 0x8e, 0xee, 0xca, 0x7b, 0xf1, 0x17, 0xb6, 0xda, 0x31, 0xe8, 0xe0, 0x6b, 0xb0, 0xf5,
	0x18, 0xe0, 0xa4, 0x25, 0x6c, 0x0d, 0x96, 0xf7, 0xe4, 0x08, 0x3f, 0xb4, 0xbe, 0x83, 0x7e, 0x3d,
	0xcd, 0xf8, 0xb4, 0xad, 0xfa, 0x63, 0xc2, 0xbd, 0x49, 0x58, 0xfd, 0x88, 0xb0, 0xf9, 0x11, 0x61,
	0xa4, 0x7f, 0x44, 0xd0, 0xb9, 0x3b, 0x35, 0xc8, 0xab, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a,
	0xe6, 0x05, 0x34, 0x56, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	AddRole(ctx context.Context, in *AddRoleRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/srv.users.UsersService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/srv.users.UsersService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) AddRole(ctx context.Context, in *AddRoleRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/srv.users.UsersService/AddRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	AddRole(context.Context, *AddRoleRequest) (*empty.Empty, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUsersServiceServer) Auth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedUsersServiceServer) AddRole(ctx context.Context, req *AddRoleRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRole not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srv.users.UsersService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srv.users.UsersService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_AddRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).AddRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srv.users.UsersService/AddRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).AddRole(ctx, req.(*AddRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "srv.users.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UsersService_CreateUser_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _UsersService_Auth_Handler,
		},
		{
			MethodName: "AddRole",
			Handler:    _UsersService_AddRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "srv-users/server.proto",
}
