// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: srv-users/server.proto

package srv_users

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AuthRequest) Validate() error {
	return nil
}
func (this *AuthResponse) Validate() error {
	for _, item := range this.Errors {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Errors", err)
			}
		}
	}
	return nil
}
func (this *Error) Validate() error {
	return nil
}
func (this *CreateUserRequest) Validate() error {
	return nil
}
func (this *CreateUserResponse) Validate() error {
	return nil
}
